### ISSUE TITLE
Cannot read property '1' of null

### ISSUE THREAD

**Issue by michaelwschultz** [jhewt/gumer-psn#19]
Looking to build a simple PSN friends list menubar app with notifications and such myself. Nice work so far!

```
Starting gPSN
gPSN | Getting login
express deprecated router.param(fn): Refactor to use path params node_modules/express/lib/application.js:331:16
gumerPSN Example running at http://localhost:3000/
gPSN | Logging in, sending POST
gPSN | Logged in, following redirects
/Users/michael/Dev/gumer-psn/psn.js:132
				getAccessToken(codeResult[1])
				                         ^
TypeError: Cannot read property '1' of null
    at Request._callback (/Users/michael/Dev/gumer-psn/psn.js:132:30)
    at Request.self.callback (/Users/michael/Dev/gumer-psn/node_modules/request/request.js:198:22)
    at Request.emit (events.js:110:17)
    at Request.<anonymous> (/Users/michael/Dev/gumer-psn/node_modules/request/request.js:1073:14)
    at Request.emit (events.js:129:20)
    at IncomingMessage.<anonymous> (/Users/michael/Dev/gumer-psn/node_modules/request/request.js:1019:12)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)
```

**Comment by jhewt** [comment]
Have you changed the login details on the top of the example file?

**Comment by jhewt** [comment]
Any updates on this? I'm closing it for now.
