### ISSUE TITLE
TypeError: Cannot read property '1' of null

### ISSUE THREAD

**Issue by techpulse** [jhewt/gumer-psn#24]
ypeError: Cannot read property '1' of null
    at Request._callback (/root/node_modules/gumer-psn/psn.js:132:30)
    at Request.self.callback (/root/node_modules/gumer-psn/node_modules/request/request.js:198:22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (/root/node_modules/gumer-psn/node_modules/request/request.js:1035:10)
    at Request.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/root/node_modules/gumer-psn/node_modules/request/request.js:962:12)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:944:16
    at process._tickCallback (node.js:442:13)
[root@ns3009754 gumer-psn]# nano index.js
[root@ns3009754 gumer-psn]# node index.js
Starting gPSN
gPSN | Getting login
gumerPSN Example running at http://localhost:3000/
gPSN | Logging in, sending POST
gPSN | Logged in, following redirects

TypeError: Cannot read property '1' of null
    at Request._callback (/root/node_modules/gumer-psn/psn.js:132:30)
    at Request.self.callback (/root/node_modules/gumer-psn/node_modules/request/request.js:198:22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (/root/node_modules/gumer-psn/node_modules/request/request.js:1035:10)
    at Request.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/root/node_modules/gumer-psn/node_modules/request/request.js:962:12)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:944:16
    at process._tickCallback (node.js:442:13)

**Comment by tlrmcknz** [comment]
Happens to me only when token has expired.

**Comment by Senaxx** [comment]
I have it here on initial startup. 

admin@NAS:~/node_modules/gumer-psn$ node index.js
Starting gPSN
gPSN | Getting login
express deprecated router.param(fn): Refactor to use path params node_modules/express/lib/application.js:331:16
gumerPSN Example running at http://localhost:3000/
gPSN | Logging in, sending POST
gPSN | Logged in, following redirects
/volume1/homes/admin/node_modules/gumer-psn/psn.js:132
                                getAccessToken(codeResult[1])
                                                         ^

TypeError: Cannot read property '1' of null
    at Request._callback (/volume1/homes/admin/node_modules/gumer-psn/psn.js:132:30)
    at Request.self.callback (/volume1/homes/admin/node_modules/gumer-psn/node_modules/request/request.js:199:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/volume1/homes/admin/node_modules/gumer-psn/node_modules/request/request.js:1036:10)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/volume1/homes/admin/node_modules/gumer-psn/node_modules/request/request.js:963:12)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)

**Comment by QuantumImmortality** [comment]
I've got this exact same problem, I'm currently trying to see if I can create a work around for this issue. I tried getting it to loop and get a new token but that stopped my actual scrapping, so I'm trying it through a different means

**Comment by QuantumImmortality** [comment]
Ok, I 'fixed' the problem in a sense. I don't believe there are any repercussions in terms of refreshing the token more frequently than once an hour. For me, this problem occurs not at every token refresh, so this fix was based with that in mind. I shortened the refresh delay to ~15 minutes (unlikely for 4 failures) and now I have had the code running for the entire day with no stoppage (this was with refresh at ~ 7.5minutes instead of 15)/

`function getAccessToken(authCode, callback) {
    debug('Getting access token');
    var responseJSON;
    if (refreshToken.length > 0) {
        request.post(psnURL.oauth, {
            form: { // Refreshing the token with refresh_token to avoid login again
                'grant_type': 'refresh_token'
                    , 'client_id': psnVars.client_id
                    , 'client_secret': psnVars.client_secret
                    , 'refresh_token': refreshToken
                    , 'redirect_uri': psnVars.redirectURL_oauth
                    , 'state': 'x'
                    , 'scope': psnVars.scope_psn
                    , 'duid': psnVars.duid
            }
        }, function (error, response, body) {
            console.log("---------------------------------- " + body) //used when requesting a refreshed access token
            if (body == undefined) {
                console.log("||||||||||||||||| und" + authCode);
                callback();
            }
            else {
                responseJSON = JSON.parse(body);
                if (!error) {
                    if ('access_token' in responseJSON && !('error' in responseJSON) && responseJSON != 'undefined') {
                        console.log("halp");
                        accessToken = responseJSON.access_token;
                        refreshToken = responseJSON.refresh_token;
                        debug('access_token obtained by using refresh_token: ' + accessToken)
                        if (typeof callback === "function") callback();
                    }
                    else {
                        debug('ERROR==: ' + responseJSON)
                    }
                }

                else {
                    debug('ERROR++: ' + error)
                }
            }
        })
    }
    else {
        debug('Login for the first time');
        request.post(psnURL.oauth, {
            form: { // Firts time login
                'grant_type': 'authorization_code'
                    , 'client_id': psnVars.client_id
                    , 'client_secret': psnVars.client_secret
                    , 'code': authCode
                    , 'redirect_uri': psnVars.redirectURL_oauth
                    , 'state': 'x'
                    , 'scope': psnVars.scope_psn
                    , 'duid': psnVars.duid
            }
        }, function (error, response, body) {
            responseJSON = JSON.parse(body);
            if (!error) {
                if ('access_token' in responseJSON && !('error' in responseJSON)) {
                    accessToken = responseJSON.access_token;
                    refreshToken = responseJSON.refresh_token;
                    clearInterval(refreshInterval);
                    refreshInterval = setInterval(function () {
                        getAccessToken(accessToken, function () {
                            debug('access_token refreshed after 59 minutes')
                        })
                    }, (responseJSON.expires_in - 60) * 250) // ~15 minutes 
                    debug('access_token/refresh_token obtained: ' + body);
                    if (typeof callback === "function") callback();
                }
                else {
                    debug('ERROR: ' + JSON.stringify(responseJSON))
                }
            }
            else {
                debug('ERROR: ' + JSON.stringify(error))
            }
        })
    }
}`

**Comment by techpulse** [comment]
`[root@server gumer-psn]# node index.js
Starting gPSN
gPSN | Getting login
express deprecated router.param(fn): Refactor to use path params node_modules/express/lib/application.js:331:16
gumerPSN Example running at http://localhost:3000/
gPSN | Logging in, sending POST
gPSN | Logged in, following redirects

TypeError: Cannot read property '1' of null
    at Request._callback (/root/node_modules/gumer-psn/psn.js:132:30)
    at Request.self.callback (/root/node_modules/gumer-psn/node_modules/request/request.js:187:22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (/root/node_modules/gumer-psn/node_modules/request/request.js:1048:10)
    at Request.emit (events.js:95:17)
    at IncomingMessage.<anonymous> (/root/node_modules/gumer-psn/node_modules/request/request.js:969:12)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:944:16
    at process._tickCallback (node.js:458:13)
`

**Comment by techpulse** [comment]
Getting it at login now, any ideas guys?
