### ISSUE TITLE
Not working anymore

### ISSUE THREAD

**Issue by vandalnet** [jhewt/gumer-psn#28]
When initiating, it says:

gPSN | Logging in, sending POST
gPSN | Logged in, following redirects

TypeError: Cannot read property '1' of null
    at Request._callback (/root/psnapi2/gumer-psn-6fbe8fbf225ed7517154617e58f1770467ce1eee/psn.js:132:30)
    at Request.self.callback (/root/psnapi2/gumer-psn-6fbe8fbf225ed7517154617e58f1770467ce1eee/node_modules/request/request.js:198:22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (/root/psnapi2/gumer-psn-6fbe8fbf225ed7517154617e58f1770467ce1eee/node_modules/request/request.js:1073:14)
    at Request.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/root/psnapi2/gumer-psn-6fbe8fbf225ed7517154617e58f1770467ce1eee/node_modules/request/request.js:1019:12)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:944:16
    at process._tickCallback (node.js:448:13)

**Comment by techpulse** [comment]
same

**Comment by vandalnet** [comment]
I actually fixed it accepting the new SEN Terms of Service, maybe you have the same problem

**Comment by jhewt** [comment]
Thanks @vandalnet,

We may need to implement a detection when they change the ToS, so it doesn't end in a fatal crash.
At some point I'll be upgrading the library to ES2015 and accept the pending pull requests, so there's a chance to add the detection.

**Comment by techpulse** [comment]
wow yeah, is there any way to make it auto refresh token every 30 min though?
