### ISSUE TITLE
Cannot read property '1' of null

### ISSUE THREAD

**Issue by RareSecond** [jhewt/gumer-psn#36]
```
gPSN | Invalid "eu" region value, using "us" instead
gPSN | Getting login
gPSN | Logging in, sending POST
gPSN | Logged in, following redirects
/Users/jasperdansercoer/kayzrapi/node_modules/gumer-psn/psn.js:132
				getAccessToken(codeResult[1])
				                         ^

TypeError: Cannot read property '1' of null
    at Request._callback (/Users/jasperdansercoer/kayzrapi/node_modules/gumer-psn/psn.js:132:30)
    at Request.self.callback (/Users/jasperdansercoer/kayzrapi/node_modules/request/request.js:188:22)
    at emitTwo (events.js:125:13)
    at Request.emit (events.js:213:7)
    at Request.<anonymous> (/Users/jasperdansercoer/kayzrapi/node_modules/request/request.js:1171:10)
    at emitOne (events.js:115:13)
    at Request.emit (events.js:210:7)
    at IncomingMessage.<anonymous> (/Users/jasperdansercoer/kayzrapi/node_modules/request/request.js:1091:12)
    at Object.onceWrapper (events.js:314:30)
    at emitNone (events.js:110:20)
    at IncomingMessage.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1047:12)
    at _combinedTickCallback (internal/process/next_tick.js:102:11)
    at process._tickDomainCallback (internal/process/next_tick.js:198:9)
```

Any idea? Is this related to my incorrect region? Because the docs don't state what the possible regions are.

**Comment by pacMakaveli** [comment]
Does your account uses 2FA?

**Comment by RareSecond** [comment]
It actually does not, it's quite an old account.

**Comment by jhewt** [comment]
Try loging in with your account in the official PSN site, you may not accepeted some ToS change.
I'm sorry I'm not able to update this repository, someday with free time I may refactor the entire code.

**Comment by OliviaB14** [comment]
did anybody fix the problem?
